credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          description: "Personal Access Token  "
          id: "github"
          password: "{AQAAABAAAAAwBXBppfJ9pE1/NW9aSW9FD+Pbbsu3vV0kYAAb07SWn/yu0MJIvH+pvpkK5ODKaBd80PYMpMsH/Lp4/jCQQPXr5A==}"
          scope: GLOBAL
          username: "tranvanloc412"
    - credentials:
      - basicSSHUserPrivateKey:
          id: "ec2-fleet"
          passphrase: "{AQAAABAAAAaQWCQYOr71b2amF4YdwZYkP5ltF5H8BzpO3x7f21R032nbsZccOfQAMLtd+4nzz5fY9zdtvlvxmMB0yA8T8Vl+JEWGAM7SYWLMtl4SKJNT7sBfAPp0A8oDP7glCT0wsn99+86kJlzO8IBhZwGP0eePFkmNfg+iMtX0l23If9pL1kTh57TMGHCJoPecDvdT2uZm5Sk4+5qhQ6jNZGIMjHfA1N0KBaYqw/BJs8e74vee+Vy2L+lWTTgiGsLo0Rd73tY8hu8Q4H6GqS0jCHQ8cQ01Lj1viTAuJBWLBMurbW/NQuEgjMrYh8kSPtdBuUIitucX1dLIJFBIN2RL+Kgp7Kxq6j0d+udPVvUw7Ic0eHQHRYUT4lXoGSQaoSpGzaYXwaNe4UjLNXC/DhNnXG9AhcGnL6GGM7PwetD77aX3R8OY1nIL8/JU78bUjrkhc3qqFWumHGr/tZwzB5Ot4m8eVklBchBnazO660JMsEKqBAR6GeoOvVgupVvYIsHqCq7SX+BVPzziuzKkS9nA/h9VmstJq1TTZwlIeCJiiP+G7mLClBsP4yuzNS7bhLccSQRZR6I2cjPJ2o3UT9VG0aGWMY4yY7K1xVAf1QOmHRUNdgiuj6yjBq1N6zlOft8VnOozsDk38P/XTO/TJoC8TAh44fig1L5QAZuNUUrSIowhnbQDfs0O1qR5uLXKNBW1HNjWkpXolds4B20johGvUjvV+inFzZMCF6k8XMdGOwuiL/eIUZEdySVXm6cE9aX4ds4AyrlU8B8A8xfJFyh7GA5tSDQkFIY4RNtEKXzGZQPVRqht2r04c799pdtHD8d9CCW8FywQ6gXp+73tT2C4uA6rpHkZRztoLGmkPZVv13PzuMD0J05VqbcOekTlb7lkAuv5Ki/GPbi/lK81Rki+ihbHzl9TnSKlS5J9EeT5EYEJgwdHSph89dhjGQKMFqxXHrf2Kc1gDuVP4H70C2BVoylaoGe3vcfJ7+ywROE9w90DtyOL4e+gszv5cAPabgfMk2S3M0SoyuhbY1ad53TiAMPhqTDuoC4QPsPqQj806xl8SO8C+Np1ECW9wMTgEbQKt8y6g/i2fjJptzi995Yme+gtPvm8ZOvTQ/sR0XZ8zJ4tzHHiRnKnHk22ub9jajYnRhK5G0MIhEBVD+rtmEsivuYBQ5mCbRIcCsQupmDbLta0OuMs4R75LLfoL2eEOnMXNjB/eQD7XN8TBLsu4A3lAjs3LM8qFb/xmkPUXRI6gZINAuGJpdxg/3BMpoAK9k31OBFjbxTOaB4jdRLeLDcq5/+Gtr9dwh/y6vT9arByMmQJNxUcGlElDj6z+FbUqOZUg1Fta4QccMwEzMpBypov+3zz/I7EVmU4LW806qfZyF35i1jRiIwFPbkSJBwLtw9IuM258422Js12Pu9Cm6z/r9Yi05UIGlE0nv5YVUhsUPEOIkV4tXkvjmmRT8sVpcFOgXTS8riAKQH7NM5MHxDAhHOhMwAiqf2ceAKl4bTSZ3O69piWhwwapeOJ3rKHj7DieHR2SbXSeW29dg/D5j7B8euZTwP8y9ItQYFChZlwPbWjGJK2+LyInWiyF91lq8iM1FU+KyARY72cu7Hvsip/mJe40aEDUMxcCtHz57T8h03ZVKPElmDAnXYX/i4XtI3NNpJLXGVZTNEx6oFy17jQB50XrD5XNOjQW3Ztv/rFedvzus1rBWmWJmp5MAjKNlnnQKL5XOnSO+euT5Ef1oRezv24fR8REIz0k0n8RBaNP/KVoCxID3yXLCOsI9Kx+0iM3w+R2Nfn5nmHwyc5bfGdwznnskyU4iv09ORF70Lq5pcM6gUIwTwaaKWPSUjpKev4kWPy6RdrquxyuMcCkJ/9EvkrfOdxQufbFsqGTPplAXgmpT7sCNLNzkQ7pN7ThseaFuBmZgVv0oA2/j9Whj5ukaZH9Pzq0kSh8cnbYcWrRxALHFATgbfPOI/6W6UHDijlopbt4LilbVFxUXrD6Shs5++mUlZgZJnFKFT3zvHzfgnhpgL+0qEMEjAu097YCE6UHFBbv3n9q0Zn6nFzW6dgUh2ILXpr7VeZBxuUUGtiZNceiD8hI4sblhq44D1HMIhDY2i5mJS4OLqMd76FRKcRSpo5hRNKwBX6O8w9b3b/EwlR+y+3rfzV7GcEHLhu/xu5uwnqI3JsvmM/XBW4iihWIIg7NRdk8ii/J3xvYgBppGIlnX/R9Zx0UcOLDd0YKp1CUOp48K43HlQL6WRicSA3OegDMhJQnw==}"
          privateKeySource:
            directEntry:
              privateKey: "{AQAAABAAAAaQ8IaVpYK8/92C2VgTMnwAFJAu3y1R1WKAKTAnzd0IpTCC6vSbW40uhDOYwamq5zIXrnn4xVCTLk5x36pYURDIJW1E6Jm/sgsVNbEJvi4UyRq5c0x6Glmpd/8ye9Xz7sCOngxfaaeA7qeApTizKJvdBQHtGLXdmlQWcwCTPwJNKqqdmeQdGj2Z82T4ditPRyqRrYG6Kg8bXKAnO4oAXgRz2Xg8iu5MsB5L4MIH/pM2xzmoBxqjDYYmxv7VrsBFpJ8kLe08iJtNA/NnhVDg3tyBnulb6MjsDwUGmmSPexbh6SVGr+IIIKTLjf6P5V5NlSyOoEiCGsiJUMD6vyphWIIip5z+83tjkKPWRFcBpbuLylKsNuuuwLBlL60b4cztmX3Q0TF4b/26Oob0DhF4tPbkfANIze021oek0SoAaHo86LoeMcTmbtB4alQLdvMvYQGBkFZRef96yKaZH6xzeOgXzDBEbtykURfeihKJ70Rzb8S4ci5c5KH7Q0zzZe1jqKu6JBZKA4EIc7HqNdiBh/qagc9AaTHBnsq9DX7Vv/1d6qYReP0Be4KaK65rBNJTs9Q1zU9MFAJWNOdzL9w4mvw1T5r8z+lekyAm6br54/BBzp4ArHIS5qssv89eY427TegAgS1vmQazGh2Jf5ex/DAQSCVYODc99uQscdoJv+5yotCHifjjyTlavL6o7ni4TRNXvj7qmmhQvFufwtVm6vK+VLquk1QQP5RwXMmSy1LPoyzl33AajNpbFv/m7MRkUKYTS4XC4OkF1RF4r+PSQ/TKtX8Rnv1qk9MbglRKUaN/Phn1GWHt2K0cD0CEGl5r0wZNnLR7ofx2gkLEa+iR0QPYYd0iIBV7O2902j47xARR1DQbuFi5iIQaWk8na1w/voNxoLMW+Np3PpM+RDPFkDCrpTJYkBaMzHHEfaMx8PubVQH9t9iTjVBhrbc7zjNiA7du61lx/furK4Y7V6BnF1vDcrULOPWtMsliCZjIazlH5XxoNs8TUh57ap4QRjMvDjp8nzVrUQ5LqznVtyCGvm0jUTOdDF7b7Zkf1h6a3T/aSwSB5RYQInAy3Aqupnw46BUTA1dU62BWaISPEvd7OXmpTWX9dhsJ9qsvEC5Qu3aal7kiqP1nUsNLtcpcmJ1TXpn9XgJg5b/xgsnCknvh+8jFSYexQ6tMkej6NAIGoRLufX+vstNUoNvRNCKQxJyEy2XxbbLMLUZ4eMpme+RiCtGzMeAkgFjK90Q4QoMcD3JwG1z0WKw2RrMxXhuuHil488q3UV48Eb48Mf3FCLJTMChbTb0in7s+cmoC1XGKCx4GUWPIQdVM8QlE/TmSWzC8cJPc46LhIHd3dOPi7JCZ46WL5/Ms6ujiAM4nCdIRnQwTrZRoENwXpzH2HTcaedbC8KfFhoOhmNMU+2pKVUg2MdPfw7TFJ2JRE2UNYWdYuRiMag/uFmTASqFdzAVhOKg00zX20O0PoDpqWrKsrJqXk76LcOBlpmBU9+K6aGtv7Zw0LTjpOL322TdFPa7JTM9qjEQrVPS7vBEOXNmChxwaRfrGa2RKF/ASV+YeDXdWU9EOPKaQV24j4+oVaVp9Le4hkZiSn5Si2/q9yjBwD4H384nGKC15c+24sRLIDUJTjtZJSMf1rBiRFWRJVqZBnIj+adW+M7JD3bp6PQMz253CPBSNEOa8dwKP1+04FZz1hRiKb8c6rR6P+n5unf7eXPHuAfepv/N+aJOcOnF/aGMkkqMkR9Vd9Jvfe/QBYPS4SVtD8QHE8DXGlZlnz1Veh2J4P+I0AUXbvSpToFpNQTn6rFZPLMERqwRr5CvbrxbbrfSqiLYdwVvzne+HwcO91fWuhWkQ+SqqE3FmZazdkO0o+98GXsm3wujzlP+SAeii6zD7ppKcKgXuANHuY/YNA7ofJyjbj7KQGjyrLl0pXYVDs/0acLA8OLWFEyVlWBeCm//QjqYa/AEw1XCqElTdx6Q+Imkk2AK6BnSaValXXUU74D9Y9Ww+judiPJwUuWbe4NGSNrz9v0k2N6wQ7/m66AzeBAKLPiaRypdluI0T3jKXUhxOIcFOaLXARypLXMcSHAtPjTUt6zbEltCdlgMkTLVC+MaoOtLFdDRaS7CFTJcfZJfaXtpCnS8u22JGERsbDO/2O7xpihfbsnA7hIWMU3IwR7GkjV6+cPyfHqNSYoFzSvbSFfZ2Y1I7Ls7/KIJpms3y7k30BriEPE6h/Jvw2PFwoJ/n9ZQra+gX0oM/tVGD2KQDBA==}"
          scope: GLOBAL
          username: "ubuntu"
      - basicSSHUserPrivateKey:
          id: "github-key"
          privateKeySource:
            directEntry:
              privateKey: "{AQAAABAAAAcwigEwzodwkX5QYqG04Qlk4M50uSLojKknXy2aYXRuM4Z5RzthhZlcMIK3xcwVEYGZWJWTFL6yKbWVN1Ke0fH4/xdszxf9IEWdp/7FvuMB19QyNJHDm3PlA5XuxUiawim5bjAIaLeqq8C9A39DtUiKQtmCPIerly2xMleV7gNttLlC67CShBpKyBAakOS/irdpgSZBXygqYEaUA+gj/mKmdY2LJBoseGV358b6sspj6jUdq0mK/oPpGphHh979B+Z8MZHYimGVk6fo2aTRYOpl/KQDXdRFLas7KC3HNDo2oYs9E8mjNNpmKwPCvPYfOn/8WZbu6bctLw3Ay/ZBEuad8Ezz5ZJQqdq2IqF+xBDKzq0YEL6f+nCIs37htXXx0/71pEvkDMFcO7aBsJnBx+mBa5kKUnhRNAG7kHDYlxs/0NCg8NaSuQPgydhgfsgdV4lvInuMgEtLa9ezE3xy3imPfqk1oKy9aVNZAG197sZNB3QteTOz/auUUuRhBcQ1M1cYxElTtMvnyuMOl9ZsjP7AtLXlFj0beXUMhMXNLN7OIRfE2ByXVuZGBJJDXwi4pQ3WhRpc+TEXSV1NsmdxtALPq5WmKQepV9tZqnVjoK5XVlQjf9SOVd9GvWpvkMFSXjf5v+y2aQurq8ow6gmShCBLyBSnw5wRvG9mg37VNEScnZxHzSnKbPtpgRHmZTn9XSXhRlpFKLGz+JzGYtP80UbZOtzdAgOjv/G/fl1uo2+ifECsx9BO/98o4lgWdwyzK/XGtH0TAQ8B/v41yk7KNMBuo+blUtsQskEk/XSasXqVRFR0yngUdIhWBfGEq2nlQwYrVFJBihaZzPanu/4/EAVpQ3/TM4VNYmavluxZyEWMqwkvDrycxCO8hQ94SfH2db5NAlQ5rRYr2ZfyJbQQVfVbZZE6mvBvMuZRv6ZvQSBlikBwawlLrlpqYJ39ikh9xURyaBCFWowT1BkF+079b4N6AtPrt9dHSbrx6JFHvWMNKlBoSFXy+xpFJAOyyxu7zvsN2C5WRoajAIvkCxaLYLgjDCznCfNsVTrvHfkhTEOqSVk+VS2L0nSNVmuOx/C54bh/+5c0jXga/2BTvSpey/sqKMygueN+khWDDfFYQvbrjiyDcWxp8nO/vSpLKgqZCq45iYvegu8wB0hmCffiqPaU2AGwtj9mkBUg6hWp49KVKW5g+Dw02iBncymwsWrJeeCYwI0+8ovDWmx+mDRxhj14kF6gyEmYom6ZaH5Gc1fV50xukqcUEKzFtd/7kjt+lJ2d/7WuGkZc7hFsK6WS9qpJQ2R7mTB0gYHU5rztyJLnl8AIK8DLt/BOIdPAMP+5vCvvofWjquo973X2C1LPjviehsjjBXEcUBozgeud40ISM8ksbQxFzREOyStBvq6jQJarhuBMKL9hIA2cZl7XzIVbFmiFPnS/RkJh+eaSjeHIc6jcv+eSt7s93MLWcIPjecid55I4Pi6P5cJY98O9gx/4EtV4lsEqWPHzyyKNhNntsKauIZI18JWS/sgkR083oDP7MuupTciZvCXwB7hy8Z/kwkb674aYUNnitLpdYCLwt9AhimEsxi3z/ORuCWZvlgM6lbaY5m4wqMrucQ+E1zGOX0Bks/1AowfDmIUH5IBBjp6N2Z9vCkWOLZTDjzr9Eap7CqtH6hpSEqQbdiCPqCoVUFjN2h0DUxHUjYw5u1q0FyLAx8lbbvi7E6mMhe3gpxjYkgEKw+jHB5hYJF/BbxVeAcyKtYE8eC9DuvTEzJW6+XVUGg8pFI97kS8yTpsYI82GyrlSEVFgmPhp2RgSGMPhLVNvzyuWeD1fYJEyS0cD5uyIGHmwkSRQGzvbi1VIhqG7oVBkvVHesLpyWUgUIuk+uHrDCKNjRaP7HPrf17wtFNgdb5G20mqKPd4+NsizGehAkSWKk2ElE2bWIjGgZWMxxN7j67b2sMoWAiAA2BG6ZYsRP45IDTeMg0uigO2eHhYeUn6eEZaRKbPYeiPnDj5FfG0GqqZiyDuTslGB9H5MoGdyE2zPJVdBOD2oTopYEBMXRPeE5PNqle2n81fXx7KY5N2JwSyKSiE4wFocjmbxg1UOvKJIVyn4xhQOPD4uHzrF5crrfEJGUC+J9unqm1RJunOdHFfx/4P6N6kGyKxFqN1vha1QkT0QpOlh6HrDHmugjWD8Uu32I2TeSvRysVcr6EfylVg5BUk0rc9HWKIZx04mOjPS7eYC7T6WJ5K7Y27ltBjeat+A2ozjZ0W7876Lf2jxg0rgBUL2L3glB0ZjZEx5BR/UuSM/uG9+yBe8ophRa8Id2Ek24WZ4QL7PQQl6uq1+Yuu9suPJYbOhZkHFa4sbf9e9lO7bcE8GIdkgDGjfQVFIObwmD9GcPdwZeQDqsrDnfFRb/NuzD8PmeVQiVuwezh/huVDrDhonJBPWa1kiS4vDeTjlgCmEAfC7GnxReAQ/ttM/xqQ0Pyp5ePZbuwg=}"
          scope: GLOBAL
          username: "github-key"
      - gitHubApp:
          appID: "210153"
          description: "jenkins-github-app"
          id: "jenkins-github-app"
          privateKey: "{AQAAABAAAAawmvXw11+mAVgarActBFLeDnnDA4siDTMeTpB59Pr0MuF+yp5H4ecRqmifJIG4OPFIIiJPR0RipAYalxTAI5j+MQVI8da20zTt+UUr+i3KgrqN9vlyKtSYC6+cG1BLz/dsgOVGOql/WDILLIv0BabtGJeRYNHoeI/iXSUbHTvl59A1jz4Cs2aWnPq0FgIAPFiTEwGKZqa40bTelUSaK/naOQ/t8Uhua3BxIJ4wAVngiQH+pLNYPNwF0iV6XSm3OQgUIVSLBOSXVs+d0hinJJxgoBdUil02VAc1rHI3V+8Qc8CaocV8idtcz9v6hFwOpjJaZyG9m5xe+lWvIFGBlkegBl8jVUghv3LLoZL2mI7HiHeS7H7HYuGirm5AfTbAhjYWGNb3B1lUcV57SYjaKoG210EzdiwynS0kbRFKxRIcRrL1o0YezCq9y5K4ByeCYz+dGMaelNcWl+ZP4ULEm7pwxzC4RpmRIzsT8lX61Ou+V79o+A2YcXN+nvcYtY3wpk3z714JpbLVZGsNnxpZidUIYwQXRetmgrDNvWlEqyAURqBmqBJC7Ddi9PpJ5bqTHsgLImSpgItju53f0qdqQ4Xpd1+o6RkUygV8nl+VQTn0/+FGh5Aa4UWuoBWG/SpbONYMq/9DDjVTG9PLEgX66ACEod1enXlsZ6Je2QLVIXwmY0EGOFciZro6qYTOmW+VMc9pofUlLiNefoFhrRHOOQkUWhgGnVEhKiApzh22X/jq2vgqqCHQWpgCdluwbQZQgpypnxfMpo1IW6bnV4RbEDPgDVwlXRjhdVDphkB7S0HweGb0dMGgmObtxlefAryjLfIPKHPc8g+m6AgtW9UKZIlAfg6vkE8SU7iNgyxIdTyZabOhG/vYSULKqEhcnHpz3IUTXa3SsOX8J+v8r7/vA73QE1IP5JupQT+kIii3cqvirHH+nuIr6g0MEnMF7h7LaG5uVBtWq6YPRe3qnxDllWuFqmf6yhnwU8pmXjGvqCMtZFpSTtTYAvdJ8j+ktpt5jBd5jdn0mVjx879cN2623E3+BNraQakh7K7vZZsbLdxFyquUbq6pnE37eCz0rbJIpAub04mY/zIAMpX0RE9LEdX1+wLuaBLJ3xDV/1Gy43rVs/rQSn5HZF3p0pcpZfrGY8hovHxLixhw7YhmSwJSOksbJ7xFGOusbEle4tg2TOR7mQZSpJrZjJ/1K9P35X6GrznJcKn7W2LJEab52jAp/YfH3CHN6E5Bwa5F6pk/FRrQ/0jx45FRZE5XqtvDMk4eB2rsq0w5F7vIDqBT2SXlgM+xesMd3TjCi6uSf64y6E5P11huSH/srZlqFSolKl0AEtkOAJtxdd2ag5BLNw2Bol5TkoQeaIb8SB7EkX1/GYzShfLN40rIzkqlZ+yAKO8QYqA7w+wsIJlrTXjj+L7xtXEs+LjN9TvQVoZ6fn0YbkjdqHrfmpddXaUVpGBpWRK4f4y1+UmFaJL53HHUVTmKd3EN2DgZnRxwriSyOojtrPqMv8GqxI1ATD4QXSvAAeKjn8zZPE2l8VtO81M3x/SCFwK1AmuiEI+Q/6PXnDvhENqQFbuDtsgULyS86hrsL7YSUSfLty1r4/DGWS8PS0uS9m+XQ7unuMub0dfJNrdKXxvOb6Q20bgMZmWbGZfnUJfxqMV1SOY9lOU6+8z5zBIr+sTBTfuqMIIPnn7+lLu877keYLgt+P5EG2l9T6uCM8deJW+HmzUgvuM3IZxcXxl2blENQu7q0wC4zMHenRAsp+nMxmWs+uyjmyJSGFD/dVU+C2kZMCtDL9aMw3eD5xars0qf1kA6yJ5pQSQHzAmPIptQjK9fZux3SVojCWb6mXYqj/PtG65QLfdiDSM+9JQPhv7j3Bo0hcFj1lweJRsqlyRX6qYYkCc716FfrO4GMgmUV6IzAap4DtaFeoBBmwg0/xegzlThKGSiFK2xS2qArOmqZ4zXdLkuRNYlkMBrWkgHNKbhnuNv/Z/qaKCDgz+trnTOD2OrVenEAe1gLrGT74eqEaAdrjRrtamYnMmQOCkNhuiuAUMz8ejPBOYUsuzSAvIBLib+wSZ5LkNZZO/GlA0EPgxE1+/Z/8nL795FRebR7VhNcfPje04c0rPC68BhkGwNT4jM25skLjuGSTxfGLklRf7p21RMOA7CEOswx4p/VcMoy2Ujy7ATZN/odSiFEKdipIu/DMi/5zyAYDsCKN2xfTW6CI9dkCNVfcgFkZ+TsU7QfNPVoUugvc1pe0FJsY3OxZcScQsX+860+UEya+ZC04mmMMMW6SgcNaAdLQHW/dw4}"
      - string:
          description: "pids-applications-personal-access-token"
          id: "pids-applications-personal-access-token"
          scope: GLOBAL
          secret: "{AQAAABAAAAAwabfvWQuaOkZTyABeuFyo42gX4oiSuDeYxXQwrdxydoC6AT9m85rlL0zZdsEXsx8cA8I5IgqvbMbZJeZyUp7oJw==}"
jenkins:
  systemMessage: "PIDS-Jenkins-Master"
  numExecutors: 0
  remotingSecurity:
    enabled: true
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ecsuser
          password: ${ADMIN_PWD}
  authorizationStrategy:
    globalMatrix:
      grantedPermissions:
        - "Overall/Read:authenticated"
        - "Job/Read:authenticated"
        - "View/Read:authenticated"
        - "Overall/Administer:authenticated"
  crumbIssuer: "standard"
  slaveAgentPort: 50000
  clouds:
  - eC2Fleet:
      addNodeOnlyIfRunning: false
      alwaysReconnect: false
      cloudStatusIntervalSec: 10
      computerConnector:
        sSHConnector:
          credentialsId: "ec2-fleet"
          launchTimeoutSeconds: 60
          maxNumRetries: 10
          port: 22
          retryWaitTime: 15
          sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
      fleet: "jenkins-slave-asg"
      idleMinutes: 30
      initOnlineCheckIntervalSec: 15
      initOnlineTimeoutSec: 180
      labelString: "tooling"
      maxSize: 1
      maxTotalUses: -1
      minSize: 0
      minSpareSize: 0
      name: "EC2-Spot-Fleet"
      numExecutors: 2
      privateIpUsed: true
      region: "ap-southeast-1"
      restrictUsage: false
      scaleExecutorsByWeight: false
security:
  sSHD:
    port: -1
unclassified:
  gitHubPluginConfig:
    configs:
    - credentialsId: "pids-applications-personal-access-token"
      manageHooks: false
      name: "pids-applications"
    hookUrl: "http://13.212.248.80:8080/github-webhook/"
jobs:
  - script: >
      job('example') {
        label('build-example-spot')
        scm {
            github('loc-org/jenkins-jobs', 'main')
        }
        triggers {
            githubPush()
        }
        steps {
            dsl(['main.groovy'])
        }
      }
  - script: >
      pipelineJob('github-demo') {
        definition {
            cpsScm {
                scm {
                    git {
                        remote {
                            github('loc-org/jenkins-jobs')
                            credentials('github')
                        }
                        branch('*/main')
                    }
                }
                scriptPath('main.groovy')
            }
        }
      }
