credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          description: "Personal Access Token  "
          id: "github"
          password: "{AQAAABAAAAAwBXBppfJ9pE1/NW9aSW9FD+Pbbsu3vV0kYAAb07SWn/yu0MJIvH+pvpkK5ODKaBd80PYMpMsH/Lp4/jCQQPXr5A==}"
          scope: GLOBAL
          username: "tranvanloc412"
      - basicSSHUserPrivateKey:
          id: "ec2-fleet"
          passphrase: "{AQAAABAAAAaQgqW/+ejCgOUPXVntfnRQI2lMEycPShXPDjxsQNqWnLHm9vhOQFpyPHElEUssjNloV4MpxYEJS8MCiAPNAcDKbSX2qOGj9vDoqdBBv4jsBUp0GK2LR3jzamG8bl9Q8Kc5mkZWnMYTW+UIlv8eeA8ZkwEYgYXL3i2mRs3x9SAcTeQ5BJIw2eHj2brf3X4se8E83bwNBWP9vrQBdTI9TBG3EMAJiCbuDzE1VQ+iCGy4aHazH1WEe3hgCwE6/6w9dcEgKvrhrGk3snBcdNvnfJcW8MhIbjVr9mO5yMjCnE9MHfGjYDGG8VMUOJOoZMPFQC2mM/IVQJ5AhlBo0s99+R/J0G5e/VBuIOmGC80nMBfxpu3OfV34F1EDLxCjNzzy082A4FlWIn37MOqQ5vFqEAL3umVHrs2v6u6mnVd3g+FgnFjpJ+GaPqD3f4nGy4xX0BFjPHRjj/9qxuDkNDpH/r53apVZ3mNNhqA91sOzZLaVspxRWRzLjH7+odDorBBbVYtRUNpoX/xex7cXjCuQ3Y83CvvKjMOltFa/ZOzvnO+ypN5/lD3WYTWFNBTTMT3DgBz156N7jQgGkxvfHa/D2ErZ1HweHEg+rqoR1b7gRYahwsiIi+/yY+hlruDo9oQw0SX0Ac6eMLFM2Vh+5LiQDDDSWL4Z8i09haz31qUvMC34M7NK9iOPcnaQHLzFaIZ+YPUuWVOiQw5iYGPU/wgmOFpz5rFzdjGwJ/0McXTccS7cEWxSashmW5LLoupvq67cZN54bUgMrSWVlzxNvev2/EyzblbZrfI/NstqrwYQ88JG9Lg2nZwKhM4oFOU/4TKUj7eDllnMvUW5M42JSffH0V9DBizczis6AOQ8ZNGSlSwdbuN9tUCxLpg74SBeWZ8Wa1EW5SWyWxBtkanjeXM+Wt6VwKqrjW0I5PYbLzNP839L652DEKOEH09swYCK3x86KvPdWVqBfRHQa+HcC+2DUFgvgNS72gew5G4HFr44UXOAdMQwH/o9WO0Wucgi3KlTo8aak3lBvx9tnPENkeci5Z/a14smjcC0EPcDXyK7KLUNGTD/AWv4Va7omUuCrGRA5Qlq9cTHeG2LIhmQncaqDoi4YdyYJ3v3f2MXv/EAw4Ft9W0WNpNf4grGqgVmaKSuv6C9xlYOayBzLAJCp8FcTJ2bNznaMF046SREtmsiowrREcCwMg12xZjJIbMougUSnHx50aQafrPtIUUVXs0cejTpBtbhth++MAG3pqMDo4uo2kPX4mPVx8Hln1+28GiOOFXXEWmxaXeDZ58KpNESsI0IgbRqXj8F6jtc8RQ5a74B2FpeKJq6CeAbuF35O9Ta8Ju26UyhdTazQeBBlvh806e5HL+IVk2Sf2OEaLiLHa6yd1AR+70mekl32xStZ0sfZSWjCK5pDpwX01AX0RPpsFTwKIJWWmB34Q/+9yJ0dIy8V5cLstSBTQxwtAYmiegCaiCJ7BPFl2SegazdmZbX7g46YFL0jwBVOJ/NaqwshY6+RHLsCLlwf3h75RcNMOwZ0NpWbM02PyBx9hHDaolwHYEeHxFWEKyDugb0QiB6bz6gKk5VWq4ZedSlf4+7N6CHtwJsflX57XKZ53hKm/954lP5QZt6+h53c2mcvARktGevPWKhWT4nY/R5e1t4fA+7rMZywvDc3OzGV4VfjWmNDHQB/Xu3q6eFxCywfjLkz01I9nK1CZ8Hp2vc1dY1Vcf/7IZizd4nH9MYaJiUu/d4Hvjbj0gKxqj+v127T73LXBSjiISHt5g9AJCXYrb284pTNFiAQNL1haNDUCjGd/9242HJJJKPeScwL6yyGNouk2aWwjd91lhFb6GVGqMyVKd+smQI/IEdQWAn0CsIXfA8BXQArpkHXCbgSnqJXH62nZoSP2Qm+rPyWX+3IzEJK2LsRRZJIRwfbT/G6oMrory4FrUmesEM3nsc/FgttHwjY6urdNEL+rBL5EvQ6WYAmjQewY+pcifQNPC9JMHF1O+2PyfG5c4SmIKkzhSkkyDwNKROt6swWmlUEuGUdy1jv31IR7VXEkbvLolR1hGMGeU1WGqqaXvDkdpaoQMdEJyd1kFB8twoB8CmSmr+a7nuO309DlYWJTCs8ZHtU/SB9daOK/f5n+wi9aiQwaJ3BEf+CCQUiYlrDFuVwSM6dMowd89Vw7hcnprmlTtxVLqyKeaiQN8So7OYvadZZL7SNnQUNeI4vo8BAc5hghqql+11DvBqv4LhkGShFf7exscHV5l2Pr/TZw==}"
          privateKeySource:
            directEntry:
              privateKey: "{AQAAABAAAAaQ8IaVpYK8/92C2VgTMnwAFJAu3y1R1WKAKTAnzd0IpTCC6vSbW40uhDOYwamq5zIXrnn4xVCTLk5x36pYURDIJW1E6Jm/sgsVNbEJvi4UyRq5c0x6Glmpd/8ye9Xz7sCOngxfaaeA7qeApTizKJvdBQHtGLXdmlQWcwCTPwJNKqqdmeQdGj2Z82T4ditPRyqRrYG6Kg8bXKAnO4oAXgRz2Xg8iu5MsB5L4MIH/pM2xzmoBxqjDYYmxv7VrsBFpJ8kLe08iJtNA/NnhVDg3tyBnulb6MjsDwUGmmSPexbh6SVGr+IIIKTLjf6P5V5NlSyOoEiCGsiJUMD6vyphWIIip5z+83tjkKPWRFcBpbuLylKsNuuuwLBlL60b4cztmX3Q0TF4b/26Oob0DhF4tPbkfANIze021oek0SoAaHo86LoeMcTmbtB4alQLdvMvYQGBkFZRef96yKaZH6xzeOgXzDBEbtykURfeihKJ70Rzb8S4ci5c5KH7Q0zzZe1jqKu6JBZKA4EIc7HqNdiBh/qagc9AaTHBnsq9DX7Vv/1d6qYReP0Be4KaK65rBNJTs9Q1zU9MFAJWNOdzL9w4mvw1T5r8z+lekyAm6br54/BBzp4ArHIS5qssv89eY427TegAgS1vmQazGh2Jf5ex/DAQSCVYODc99uQscdoJv+5yotCHifjjyTlavL6o7ni4TRNXvj7qmmhQvFufwtVm6vK+VLquk1QQP5RwXMmSy1LPoyzl33AajNpbFv/m7MRkUKYTS4XC4OkF1RF4r+PSQ/TKtX8Rnv1qk9MbglRKUaN/Phn1GWHt2K0cD0CEGl5r0wZNnLR7ofx2gkLEa+iR0QPYYd0iIBV7O2902j47xARR1DQbuFi5iIQaWk8na1w/voNxoLMW+Np3PpM+RDPFkDCrpTJYkBaMzHHEfaMx8PubVQH9t9iTjVBhrbc7zjNiA7du61lx/furK4Y7V6BnF1vDcrULOPWtMsliCZjIazlH5XxoNs8TUh57ap4QRjMvDjp8nzVrUQ5LqznVtyCGvm0jUTOdDF7b7Zkf1h6a3T/aSwSB5RYQInAy3Aqupnw46BUTA1dU62BWaISPEvd7OXmpTWX9dhsJ9qsvEC5Qu3aal7kiqP1nUsNLtcpcmJ1TXpn9XgJg5b/xgsnCknvh+8jFSYexQ6tMkej6NAIGoRLufX+vstNUoNvRNCKQxJyEy2XxbbLMLUZ4eMpme+RiCtGzMeAkgFjK90Q4QoMcD3JwG1z0WKw2RrMxXhuuHil488q3UV48Eb48Mf3FCLJTMChbTb0in7s+cmoC1XGKCx4GUWPIQdVM8QlE/TmSWzC8cJPc46LhIHd3dOPi7JCZ46WL5/Ms6ujiAM4nCdIRnQwTrZRoENwXpzH2HTcaedbC8KfFhoOhmNMU+2pKVUg2MdPfw7TFJ2JRE2UNYWdYuRiMag/uFmTASqFdzAVhOKg00zX20O0PoDpqWrKsrJqXk76LcOBlpmBU9+K6aGtv7Zw0LTjpOL322TdFPa7JTM9qjEQrVPS7vBEOXNmChxwaRfrGa2RKF/ASV+YeDXdWU9EOPKaQV24j4+oVaVp9Le4hkZiSn5Si2/q9yjBwD4H384nGKC15c+24sRLIDUJTjtZJSMf1rBiRFWRJVqZBnIj+adW+M7JD3bp6PQMz253CPBSNEOa8dwKP1+04FZz1hRiKb8c6rR6P+n5unf7eXPHuAfepv/N+aJOcOnF/aGMkkqMkR9Vd9Jvfe/QBYPS4SVtD8QHE8DXGlZlnz1Veh2J4P+I0AUXbvSpToFpNQTn6rFZPLMERqwRr5CvbrxbbrfSqiLYdwVvzne+HwcO91fWuhWkQ+SqqE3FmZazdkO0o+98GXsm3wujzlP+SAeii6zD7ppKcKgXuANHuY/YNA7ofJyjbj7KQGjyrLl0pXYVDs/0acLA8OLWFEyVlWBeCm//QjqYa/AEw1XCqElTdx6Q+Imkk2AK6BnSaValXXUU74D9Y9Ww+judiPJwUuWbe4NGSNrz9v0k2N6wQ7/m66AzeBAKLPiaRypdluI0T3jKXUhxOIcFOaLXARypLXMcSHAtPjTUt6zbEltCdlgMkTLVC+MaoOtLFdDRaS7CFTJcfZJfaXtpCnS8u22JGERsbDO/2O7xpihfbsnA7hIWMU3IwR7GkjV6+cPyfHqNSYoFzSvbSFfZ2Y1I7Ls7/KIJpms3y7k30BriEPE6h/Jvw2PFwoJ/n9ZQra+gX0oM/tVGD2KQDBA==}"
          scope: GLOBAL
          username: "ubuntu"
      - basicSSHUserPrivateKey:
          id: "github-key"
          privateKeySource:
            directEntry:
              privateKey: "{AQAAABAAAAcwigEwzodwkX5QYqG04Qlk4M50uSLojKknXy2aYXRuM4Z5RzthhZlcMIK3xcwVEYGZWJWTFL6yKbWVN1Ke0fH4/xdszxf9IEWdp/7FvuMB19QyNJHDm3PlA5XuxUiawim5bjAIaLeqq8C9A39DtUiKQtmCPIerly2xMleV7gNttLlC67CShBpKyBAakOS/irdpgSZBXygqYEaUA+gj/mKmdY2LJBoseGV358b6sspj6jUdq0mK/oPpGphHh979B+Z8MZHYimGVk6fo2aTRYOpl/KQDXdRFLas7KC3HNDo2oYs9E8mjNNpmKwPCvPYfOn/8WZbu6bctLw3Ay/ZBEuad8Ezz5ZJQqdq2IqF+xBDKzq0YEL6f+nCIs37htXXx0/71pEvkDMFcO7aBsJnBx+mBa5kKUnhRNAG7kHDYlxs/0NCg8NaSuQPgydhgfsgdV4lvInuMgEtLa9ezE3xy3imPfqk1oKy9aVNZAG197sZNB3QteTOz/auUUuRhBcQ1M1cYxElTtMvnyuMOl9ZsjP7AtLXlFj0beXUMhMXNLN7OIRfE2ByXVuZGBJJDXwi4pQ3WhRpc+TEXSV1NsmdxtALPq5WmKQepV9tZqnVjoK5XVlQjf9SOVd9GvWpvkMFSXjf5v+y2aQurq8ow6gmShCBLyBSnw5wRvG9mg37VNEScnZxHzSnKbPtpgRHmZTn9XSXhRlpFKLGz+JzGYtP80UbZOtzdAgOjv/G/fl1uo2+ifECsx9BO/98o4lgWdwyzK/XGtH0TAQ8B/v41yk7KNMBuo+blUtsQskEk/XSasXqVRFR0yngUdIhWBfGEq2nlQwYrVFJBihaZzPanu/4/EAVpQ3/TM4VNYmavluxZyEWMqwkvDrycxCO8hQ94SfH2db5NAlQ5rRYr2ZfyJbQQVfVbZZE6mvBvMuZRv6ZvQSBlikBwawlLrlpqYJ39ikh9xURyaBCFWowT1BkF+079b4N6AtPrt9dHSbrx6JFHvWMNKlBoSFXy+xpFJAOyyxu7zvsN2C5WRoajAIvkCxaLYLgjDCznCfNsVTrvHfkhTEOqSVk+VS2L0nSNVmuOx/C54bh/+5c0jXga/2BTvSpey/sqKMygueN+khWDDfFYQvbrjiyDcWxp8nO/vSpLKgqZCq45iYvegu8wB0hmCffiqPaU2AGwtj9mkBUg6hWp49KVKW5g+Dw02iBncymwsWrJeeCYwI0+8ovDWmx+mDRxhj14kF6gyEmYom6ZaH5Gc1fV50xukqcUEKzFtd/7kjt+lJ2d/7WuGkZc7hFsK6WS9qpJQ2R7mTB0gYHU5rztyJLnl8AIK8DLt/BOIdPAMP+5vCvvofWjquo973X2C1LPjviehsjjBXEcUBozgeud40ISM8ksbQxFzREOyStBvq6jQJarhuBMKL9hIA2cZl7XzIVbFmiFPnS/RkJh+eaSjeHIc6jcv+eSt7s93MLWcIPjecid55I4Pi6P5cJY98O9gx/4EtV4lsEqWPHzyyKNhNntsKauIZI18JWS/sgkR083oDP7MuupTciZvCXwB7hy8Z/kwkb674aYUNnitLpdYCLwt9AhimEsxi3z/ORuCWZvlgM6lbaY5m4wqMrucQ+E1zGOX0Bks/1AowfDmIUH5IBBjp6N2Z9vCkWOLZTDjzr9Eap7CqtH6hpSEqQbdiCPqCoVUFjN2h0DUxHUjYw5u1q0FyLAx8lbbvi7E6mMhe3gpxjYkgEKw+jHB5hYJF/BbxVeAcyKtYE8eC9DuvTEzJW6+XVUGg8pFI97kS8yTpsYI82GyrlSEVFgmPhp2RgSGMPhLVNvzyuWeD1fYJEyS0cD5uyIGHmwkSRQGzvbi1VIhqG7oVBkvVHesLpyWUgUIuk+uHrDCKNjRaP7HPrf17wtFNgdb5G20mqKPd4+NsizGehAkSWKk2ElE2bWIjGgZWMxxN7j67b2sMoWAiAA2BG6ZYsRP45IDTeMg0uigO2eHhYeUn6eEZaRKbPYeiPnDj5FfG0GqqZiyDuTslGB9H5MoGdyE2zPJVdBOD2oTopYEBMXRPeE5PNqle2n81fXx7KY5N2JwSyKSiE4wFocjmbxg1UOvKJIVyn4xhQOPD4uHzrF5crrfEJGUC+J9unqm1RJunOdHFfx/4P6N6kGyKxFqN1vha1QkT0QpOlh6HrDHmugjWD8Uu32I2TeSvRysVcr6EfylVg5BUk0rc9HWKIZx04mOjPS7eYC7T6WJ5K7Y27ltBjeat+A2ozjZ0W7876Lf2jxg0rgBUL2L3glB0ZjZEx5BR/UuSM/uG9+yBe8ophRa8Id2Ek24WZ4QL7PQQl6uq1+Yuu9suPJYbOhZkHFa4sbf9e9lO7bcE8GIdkgDGjfQVFIObwmD9GcPdwZeQDqsrDnfFRb/NuzD8PmeVQiVuwezh/huVDrDhonJBPWa1kiS4vDeTjlgCmEAfC7GnxReAQ/ttM/xqQ0Pyp5ePZbuwg=}"
          scope: SYSTEM
          username: "github-key"
jenkins:
  systemMessage: "PIDS-Jenkins-Master"
  numExecutors: 0
  remotingSecurity:
    enabled: true
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ecsuser
          password: ${ADMIN_PWD}
  authorizationStrategy:
    globalMatrix:
      grantedPermissions:
        - "Overall/Read:authenticated"
        - "Job/Read:authenticated"
        - "View/Read:authenticated"
        - "Overall/Administer:authenticated"
  crumbIssuer: "standard"
  slaveAgentPort: 50000
  clouds:
  - eC2Fleet:
      addNodeOnlyIfRunning: false
      alwaysReconnect: false
      cloudStatusIntervalSec: 10
      computerConnector:
        sSHConnector:
          credentialsId: "ec2-fleet"
          launchTimeoutSeconds: 60
          maxNumRetries: 10
          port: 22
          retryWaitTime: 15
          sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
      fleet: "jenkins-slave-asg"
      idleMinutes: 30
      initOnlineCheckIntervalSec: 15
      initOnlineTimeoutSec: 180
      labelString: "tooling"
      maxSize: 1
      maxTotalUses: -1
      minSize: 0
      minSpareSize: 0
      name: "EC2-Spot-Fleet"
      numExecutors: 2
      privateIpUsed: true
      region: "ap-southeast-1"
      restrictUsage: false
      scaleExecutorsByWeight: false
security:
  sSHD:
    port: -1
jobs:
  - script: >
      job('example') {
        label('build-example-spot')
        scm {
            github('loc-org/jenkins-jobs', 'main')
        }
        triggers {
            githubPush()
        }
        steps {
            dsl(['main.groovy'])
        }
      }
  - script: >
      pipelineJob('github-demo') {
        definition {
            cpsScm {
                scm {
                    git {
                        remote {
                            github('loc-org/jenkins-jobs')
                            credentials('github')
                        }
                        branch('*/main')
                    }
                }
                scriptPath('main.groovy')
            }
        }
      }
