jenkins:
  systemMessage: "Amazon Fargate Demo"
  numExecutors: 0
  remotingSecurity:
    enabled: true
  agentProtocols:
    - "JNLP4-connect"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ecsuser
          password: ${ADMIN_PWD}
  authorizationStrategy:
    globalMatrix:
      grantedPermissions:
        - "Overall/Read:authenticated"
        - "Job/Read:authenticated"
        - "View/Read:authenticated"
        - "Overall/Administer:authenticated"
  crumbIssuer: "standard"
  slaveAgentPort: 50000
  clouds:
    - ecs:
        allowedOverrides: "inheritFrom,label,memory,cpu,image"
        credentialsId: ""
        cluster: arn:aws:ecs:ap-southeast-1:398692602192:cluster/pids-ci-spot
        name: "fargate-cloud-spot"
        regionName: ap-southeast-1
        retentionTimeout: 10
        jenkinsUrl: "http://controller.pids-ci:8080"
        templates:
          - assignPublicIp: true
            cpu: "512"
            image: "jenkins/inbound-agent"
            label: "build-example-spot"
            executionRole: arn:aws:iam::398692602192:role/pids-ci-ecs-execution-role
            launchType: "FARGATE"
            memory: 0
            memoryReservation: 1024
            networkMode: "awsvpc"
            privileged: false
            remoteFSRoot: "/home/jenkins"
            securityGroups: sg-005a9da8b944ccf41
            sharedMemorySize: 0
            subnets: subnet-09d6725ac672682ee,subnet-0c8c9e8c5fae7356a,subnet-0ec4e135306025c55
            templateName: "build-example"
            uniqueRemoteFSRoot: false
    - ecs:
        allowedOverrides: "inheritFrom,label,memory,cpu,image"
        credentialsId: ""
        cluster: arn:aws:ecs:ap-southeast-1:398692602192:cluster/pids-ci-main
        name: "fargate-cloud"
        regionName: ap-southeast-1
        retentionTimeout: 10
        jenkinsUrl: "http://controller.pids-ci:8080"
        templates:
          - assignPublicIp: true
            cpu: "512"
            image: "jenkins/inbound-agent"
            label: "build-example"
            executionRole: arn:aws:iam::398692602192:role/pids-ci-ecs-execution-role
            launchType: "FARGATE"
            memory: 0
            memoryReservation: 1024
            networkMode: "awsvpc"
            privileged: false
            remoteFSRoot: "/home/jenkins"
            securityGroups: sg-005a9da8b944ccf41
            sharedMemorySize: 0
            subnets: subnet-09d6725ac672682ee,subnet-0c8c9e8c5fae7356a,subnet-0ec4e135306025c55
            templateName: "build-example"
            uniqueRemoteFSRoot: false
security:
  sSHD:
    port: -1
jobs:
  - script: >
      pipelineJob('Simple job critical task') {
        definition {
          cps {
            script('''
              pipeline {
                  agent {
                      ecs {
                          inheritFrom 'build-example'
                      }
                  }
                  stages {
                    stage('Test') {
                        steps {
                            script {
                                sh "echo this was executed on non spot instance"
                            }
                            sh 'sleep 120'
                            sh 'echo sleep is done'
                        }
                    }
                  }
              }'''.stripIndent())
              sandbox()
          }
        }
      }
  - script: >
      pipelineJob('Simple job non critical task') {
        definition {
          cps {
            script('''
              pipeline {
                  agent {
                      ecs {
                          inheritFrom 'build-example-spot'
                      }
                  }
                  stages {
                    stage('Test') {
                        steps {
                            script {
                                sh "echo this was executed on a spot instance"
                            }
                            sh 'sleep 120'
                            sh 'echo sleep is done'
                        }
                    }
                  }
              }'''.stripIndent())
              sandbox()
          }
        }
      }
